'!include <C4/C4_Container>

@startuml pivasik
''https://plantuml.com/class-diagram

class pivo

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}
'

'artifact "chat-window.fxml"
'
'class Controller
'
'"chat-window.fxml" -> Controller

@enduml


@startuml

class Controller

allowmixing

artifact "chat-window-fxml"

"chat-window-fxml" -> Controller

@enduml

@startuml
'!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include <C4/C4_Context>

title System Context Diagram

@enduml

@startuml C4_Elements
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!include <C4/C4_Container>

Person(personAlias, "Label", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")

Rel(personAlias, containerAlias, "Label", "Optional Technology")
@enduml

@startuml Basic Sample
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <C4/C4_Container>


Person(admin, "Administrator")
System_Boundary(c1, "Sample System") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")
@enduml

@startuml
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!include <C4/C4_Container>


'!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
'!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
'!include DEVICONS/angular.puml
'!include DEVICONS/java.puml
'!include DEVICONS/msql_server.puml
'!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

Person(user, "Customer", "People that need products", $sprite="users")
Container(spa, "SPA", "angular", "The main interface that the customer interacts with", $sprite="angular")
Container(api, "API", "java", "Handles all business logic", $sprite="java")
ContainerDb(db, "Database", "Microsoft SQL", "Holds product, order and invoice information", $sprite="msql_server")

Rel(user, spa, "Uses", "https")
Rel(spa, api, "Uses", "https")
Rel_R(api, db, "Reads/Writes")
@enduml

@startuml Basic Sample
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!include <C4/C4_Container>


Person(admin, "Administrator", $sprite="person2", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md#hide_person_sprite-or-show_person_spritesprite")
System_Boundary(c1, "Sample System", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", $descr="Allows users to compare multiple Twitter timelines", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
}
System(twitter, "Twitter", $link="https://github.com/plantuml-stdlib/C4-PlantUML")

Rel(admin, web_app, "Uses", "HTTPS", $link="https://plantuml.com/link")
Rel(web_app, twitter, "Gets tweets from", "HTTPS", $link="https://plantuml.com/link")
@enduml

'Person(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
'Person_Ext(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
'System(alias, label, ?descr, ?sprite, ?tags, ?link, ?type, ?baseShape)
'SystemDb(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
'SystemQueue(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
'System_Ext(alias, label, ?descr, ?sprite, ?tags, ?link, ?type, ?baseShape)
'SystemDb_Ext(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
'SystemQueue_Ext(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
'Boundary(alias, label, ?type, ?tags, ?link, ?descr)
'Enterprise_Boundary(alias, label, ?tags, ?link, ?descr)
'System_Boundary(alias, label, ?tags, ?link, ?descr)

'Container(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link, ?baseShape)
'ContainerDb(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link)
'ContainerQueue(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link)
'Container_Ext(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link, ?baseShape)
'ContainerDb_Ext(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link)
'ContainerQueue_Ext(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link)
'Container_Boundary(alias, label, ?tags, ?link, ?descr)

'Component(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link, ?baseShape)
'ComponentDb(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link)
'ComponentQueue(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link)
'Component_Ext(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link, ?baseShape)
'ComponentDb_Ext(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link)
'ComponentQueue_Ext(alias, label, ?techn, ?descr, ?sprite, ?tags, ?link)